/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkloadRouteImport } from './routes/_app.workload'
import { Route as AppTimeRouteImport } from './routes/_app.time'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AppSprintsRouteImport } from './routes/_app.sprints'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppPeopleRouteImport } from './routes/_app.people'
import { Route as AppOnboardingRouteImport } from './routes/_app.onboarding'
import { Route as AppOnCallRouteImport } from './routes/_app.on-call'
import { Route as AppIncidentsRouteImport } from './routes/_app.incidents'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'
import { Route as AppAutomationsRouteImport } from './routes/_app.automations'
import { Route as AppTasksIdRouteImport } from './routes/_app.tasks.$id'
import { Route as AppProjectsIdRouteImport } from './routes/_app.projects.$id'
import { Route as AppIncidentsIdRouteImport } from './routes/_app.incidents.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkloadRoute = AppWorkloadRouteImport.update({
  id: '/workload',
  path: '/workload',
  getParentRoute: () => AppRoute,
} as any)
const AppTimeRoute = AppTimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSprintsRoute = AppSprintsRouteImport.update({
  id: '/sprints',
  path: '/sprints',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleRoute = AppPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppOnCallRoute = AppOnCallRouteImport.update({
  id: '/on-call',
  path: '/on-call',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsRoute = AppIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationsRoute = AppAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksIdRoute = AppTasksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTasksRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppIncidentsIdRoute = AppIncidentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppIncidentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/automations': typeof AppAutomationsRoute
  '/calendar': typeof AppCalendarRoute
  '/dashboard': typeof AppDashboardRoute
  '/incidents': typeof AppIncidentsRouteWithChildren
  '/on-call': typeof AppOnCallRoute
  '/onboarding': typeof AppOnboardingRoute
  '/people': typeof AppPeopleRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/sprints': typeof AppSprintsRoute
  '/tasks': typeof AppTasksRouteWithChildren
  '/time': typeof AppTimeRoute
  '/workload': typeof AppWorkloadRoute
  '/incidents/$id': typeof AppIncidentsIdRoute
  '/projects/$id': typeof AppProjectsIdRoute
  '/tasks/$id': typeof AppTasksIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/automations': typeof AppAutomationsRoute
  '/calendar': typeof AppCalendarRoute
  '/dashboard': typeof AppDashboardRoute
  '/incidents': typeof AppIncidentsRouteWithChildren
  '/on-call': typeof AppOnCallRoute
  '/onboarding': typeof AppOnboardingRoute
  '/people': typeof AppPeopleRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/sprints': typeof AppSprintsRoute
  '/tasks': typeof AppTasksRouteWithChildren
  '/time': typeof AppTimeRoute
  '/workload': typeof AppWorkloadRoute
  '/incidents/$id': typeof AppIncidentsIdRoute
  '/projects/$id': typeof AppProjectsIdRoute
  '/tasks/$id': typeof AppTasksIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/automations': typeof AppAutomationsRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/incidents': typeof AppIncidentsRouteWithChildren
  '/_app/on-call': typeof AppOnCallRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/people': typeof AppPeopleRoute
  '/_app/projects': typeof AppProjectsRouteWithChildren
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/sprints': typeof AppSprintsRoute
  '/_app/tasks': typeof AppTasksRouteWithChildren
  '/_app/time': typeof AppTimeRoute
  '/_app/workload': typeof AppWorkloadRoute
  '/_app/incidents/$id': typeof AppIncidentsIdRoute
  '/_app/projects/$id': typeof AppProjectsIdRoute
  '/_app/tasks/$id': typeof AppTasksIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/automations'
    | '/calendar'
    | '/dashboard'
    | '/incidents'
    | '/on-call'
    | '/onboarding'
    | '/people'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/sprints'
    | '/tasks'
    | '/time'
    | '/workload'
    | '/incidents/$id'
    | '/projects/$id'
    | '/tasks/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/automations'
    | '/calendar'
    | '/dashboard'
    | '/incidents'
    | '/on-call'
    | '/onboarding'
    | '/people'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/sprints'
    | '/tasks'
    | '/time'
    | '/workload'
    | '/incidents/$id'
    | '/projects/$id'
    | '/tasks/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/automations'
    | '/_app/calendar'
    | '/_app/dashboard'
    | '/_app/incidents'
    | '/_app/on-call'
    | '/_app/onboarding'
    | '/_app/people'
    | '/_app/projects'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/sprints'
    | '/_app/tasks'
    | '/_app/time'
    | '/_app/workload'
    | '/_app/incidents/$id'
    | '/_app/projects/$id'
    | '/_app/tasks/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workload': {
      id: '/_app/workload'
      path: '/workload'
      fullPath: '/workload'
      preLoaderRoute: typeof AppWorkloadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/time': {
      id: '/_app/time'
      path: '/time'
      fullPath: '/time'
      preLoaderRoute: typeof AppTimeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sprints': {
      id: '/_app/sprints'
      path: '/sprints'
      fullPath: '/sprints'
      preLoaderRoute: typeof AppSprintsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people': {
      id: '/_app/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AppPeopleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/on-call': {
      id: '/_app/on-call'
      path: '/on-call'
      fullPath: '/on-call'
      preLoaderRoute: typeof AppOnCallRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/incidents': {
      id: '/_app/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof AppIncidentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automations': {
      id: '/_app/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AppAutomationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/$id': {
      id: '/_app/tasks/$id'
      path: '/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof AppTasksIdRouteImport
      parentRoute: typeof AppTasksRoute
    }
    '/_app/projects/$id': {
      id: '/_app/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/incidents/$id': {
      id: '/_app/incidents/$id'
      path: '/$id'
      fullPath: '/incidents/$id'
      preLoaderRoute: typeof AppIncidentsIdRouteImport
      parentRoute: typeof AppIncidentsRoute
    }
  }
}

interface AppIncidentsRouteChildren {
  AppIncidentsIdRoute: typeof AppIncidentsIdRoute
}

const AppIncidentsRouteChildren: AppIncidentsRouteChildren = {
  AppIncidentsIdRoute: AppIncidentsIdRoute,
}

const AppIncidentsRouteWithChildren = AppIncidentsRoute._addFileChildren(
  AppIncidentsRouteChildren,
)

interface AppProjectsRouteChildren {
  AppProjectsIdRoute: typeof AppProjectsIdRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsIdRoute: AppProjectsIdRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppTasksRouteChildren {
  AppTasksIdRoute: typeof AppTasksIdRoute
}

const AppTasksRouteChildren: AppTasksRouteChildren = {
  AppTasksIdRoute: AppTasksIdRoute,
}

const AppTasksRouteWithChildren = AppTasksRoute._addFileChildren(
  AppTasksRouteChildren,
)

interface AppRouteChildren {
  AppAutomationsRoute: typeof AppAutomationsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppIncidentsRoute: typeof AppIncidentsRouteWithChildren
  AppOnCallRoute: typeof AppOnCallRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPeopleRoute: typeof AppPeopleRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSprintsRoute: typeof AppSprintsRoute
  AppTasksRoute: typeof AppTasksRouteWithChildren
  AppTimeRoute: typeof AppTimeRoute
  AppWorkloadRoute: typeof AppWorkloadRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAutomationsRoute: AppAutomationsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppIncidentsRoute: AppIncidentsRouteWithChildren,
  AppOnCallRoute: AppOnCallRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPeopleRoute: AppPeopleRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSprintsRoute: AppSprintsRoute,
  AppTasksRoute: AppTasksRouteWithChildren,
  AppTimeRoute: AppTimeRoute,
  AppWorkloadRoute: AppWorkloadRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
